version: "3"
services:
  goodwe:
    container_name: goodwe-mqtt-bridge
    build: https://github.com/ellepdesk/goodwe_logging_proxy.git
    pull_policy: build
    restart: unless-stopped
    environment:
      MQTT_HOST: mosquitto
      PORT: 80
      LOGLEVEL: INFO
